# Generated by Django 2.2.4 on 2019-08-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermembership',
            old_name='membership_type',
            new_name='membership',
        ),
    ]
